"""Public contracts for PatchLoop layered memory."""

from patchloop.memory.models import (
    MEMORY_SCHEMA_VERSION,
    CompressionOperation,
    CompressionReport,
    MemoryBundle,
    MemoryHit,
    MemoryKind,
    MemoryQuery,
    MemoryRecord,
    MemoryScope,
    MemorySource,
    MemorySourceKind,
    MemoryStatus,
    compute_memory_content_hash,
    validate_supersession_chain,
)
from patchloop.memory.store import (
    MEMORY_STORE_SCHEMA_VERSION,
    MemoryStoreConflictError,
    MemoryStoreError,
    MemoryVectorIndex,
    MemoryWriteResult,
    SQLiteMemoryStore,
)
from patchloop.memory.working import (
    WORKING_MEMORY_PREFIX,
    MemoryPromotionBatch,
    WorkingMemoryBudgetError,
    WorkingMemoryEvent,
    WorkingMemoryItem,
    WorkingMemoryItemKind,
    WorkingMemoryManager,
    WorkingMemorySnapshot,
)

__all__ = [
    "MEMORY_SCHEMA_VERSION",
    "MEMORY_STORE_SCHEMA_VERSION",
    "WORKING_MEMORY_PREFIX",
    "CompressionOperation",
    "CompressionReport",
    "MemoryBundle",
    "MemoryHit",
    "MemoryKind",
    "MemoryPromotionBatch",
    "MemoryQuery",
    "MemoryRecord",
    "MemoryScope",
    "MemorySource",
    "MemorySourceKind",
    "MemoryStatus",
    "MemoryStoreConflictError",
    "MemoryStoreError",
    "MemoryVectorIndex",
    "MemoryWriteResult",
    "SQLiteMemoryStore",
    "WorkingMemoryBudgetError",
    "WorkingMemoryEvent",
    "WorkingMemoryItem",
    "WorkingMemoryItemKind",
    "WorkingMemoryManager",
    "WorkingMemorySnapshot",
    "compute_memory_content_hash",
    "validate_supersession_chain",
]
